# Generated by Django 3.0.5 on 2020-04-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_usersapiproduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersapiproduction',
            name='shortApiKey',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='usersapiproduction',
            name='code',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='usersapiproduction',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
