# Generated by Django 3.0.5 on 2020-04-02 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_auto_20200402_1209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usersapiproduction',
            old_name='shortApiKey',
            new_name='shortcodeapi',
        ),
    ]
