# Generated by Django 2.1.3 on 2018-12-22 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradas',
            name='page',
            field=models.CharField(default='Home', max_length=20),
            preserve_default=False,
        ),
    ]
